### ISSUE TITLE
PS1 error

### ISSUE THREAD

**Issue by ericcrosson-bitgo** [EricCrosson/dotfiles#4]
```shell
async_job: no such async worker: prompt_pure 
```

pesky little bugger

**Comment by ericcrosson-bitgo** [comment]
My fix appears to have broken the greyed-out nature of the command-autocomplete-from-history feature

**Comment by EricCrosson** [comment]
only in screen it appears

**Comment by EricCrosson** [comment]
Fixed, it was unnnrelated
